import { MigrationBuilder } from 'node-pg-migrate';

export async function up(pgm: MigrationBuilder): Promise<void> {
  // Таблица возможных замен упражнений
  pgm.sql(`
    CREATE TABLE exercise_substitutions (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      exercise_id INTEGER NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
      substitute_exercise_id INTEGER NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
      priority INTEGER DEFAULT 1 CHECK (priority BETWEEN 1 AND 100),
      reason substitution_reason DEFAULT 'similar_muscle_group',
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(exercise_id, substitute_exercise_id),
      CHECK (exercise_id <> substitute_exercise_id)
  );
  `);

  // Таблица периодов разгрузки
  pgm.sql(`
    CREATE TABLE deload_periods (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      start_date DATE NOT NULL CHECK (end_date IS NULL OR end_date >= start_date),
      end_date DATE,
      intensity_factor NUMERIC(3,2) DEFAULT 0.6 CHECK (intensity_factor > 0 AND intensity_factor <= 2),
      reason VARCHAR(255),
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );
  `);

  // Таблица рекомендаций по замене упражнений для пользователей
  pgm.sql(`
    CREATE TABLE exercise_recommendations (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      exercise_id INTEGER NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
      suggested_exercise_id INTEGER NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
      reason VARCHAR(255) NOT NULL,
      is_active BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      applied_at TIMESTAMPTZ,
      CHECK (exercise_id <> suggested_exercise_id)
  );
  `);

  // Индексы и триггеры
  pgm.sql(`
    CREATE INDEX idx_deload_periods_user ON deload_periods(user_id);
    CREATE INDEX idx_exercise_recommendations_user_active ON exercise_recommendations(user_id, is_active, created_at DESC);
    CREATE INDEX idx_exercise_substitutions_exercise ON exercise_substitutions(exercise_id);
    CREATE INDEX idx_exercise_substitutions_substitute ON exercise_substitutions(substitute_exercise_id);
    
    CREATE TRIGGER update_exercise_substitutions_updated_at BEFORE UPDATE ON exercise_substitutions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

    CREATE TRIGGER update_deload_periods_updated_at BEFORE UPDATE ON deload_periods FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

    CREATE TRIGGER update_exercise_recommendations_updated_at BEFORE UPDATE ON exercise_recommendations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  `);
}

export async function down(pgm: MigrationBuilder): Promise<void> {
  pgm.sql(`
    DROP TABLE IF EXISTS exercise_recommendations CASCADE;
    DROP TABLE IF EXISTS deload_periods CASCADE;
    DROP TABLE IF EXISTS exercise_substitutions CASCADE;
  `);
}