import { MigrationBuilder } from 'node-pg-migrate';

export async function up(pgm: MigrationBuilder): Promise<void> {
  // Таблица
  pgm.createTable('exercise_metric_templates', {
    id: { 
      type: 'uuid', 
      primaryKey: true, 
      default: pgm.func('gen_random_uuid()') 
    },

    exercise_id: { 
      type: 'uuid', 
      notNull: true, 
      references: 'exercises(id)', 
      onDelete: 'CASCADE' 
    },

    metric_type: { 
      type: 'metric_type', 
      notNull: true 
    },

    required: { 
      type: 'boolean', 
      notNull: true, 
      default: true 
    },

    default_value: { type: 'numeric(10,2)' },

    unit: { 
      type: 'metric', 
      notNull: true 
    },

    created_at: { 
      type: 'timestamp with time zone', 
      notNull: true, 
      default: pgm.func('CURRENT_TIMESTAMP') 
    },

    updated_at: { 
      type: 'timestamp with time zone', 
      notNull: true, 
      default: pgm.func('CURRENT_TIMESTAMP') 
    },
  }, { 
    constraints: { 
      unique: [['exercise_id', 'metric_type']], 
      check: 'default_value IS NULL OR default_value >= 0' } 
  });

  // Добавление колонки
  pgm.addColumn('exercises', {
    verbal_instruction: {
      type: 'text',
    },
  });

  // Добавление данных
  pgm.sql(`INSERT INTO exercises (id, name, description, equipment_type, verbal_instruction, is_active)
    VALUES
      (md5('fitmaster.exercise.1')::uuid, 'Приседания со штангой на плечах', 'Базовое упражнение для ног', 'barbell', 'Штанга на трапециях, спина прямая, присесть до параллели бедер с полом, встать', true),
      (md5('fitmaster.exercise.2')::uuid, 'Жим штанги лежа', 'Базовое упражнение для груди', 'barbell', 'Лежа на скамье, взять штангу чуть шире плеч, опустить к груди, выжать вверх', true),
      (md5('fitmaster.exercise.3')::uuid, 'Становая тяга', 'Базовое упражнение на спину и ноги', 'barbell', 'Ноги на ширине таза, наклон с прямой спиной, поднять штангу с пола до выпрямления', true),
      (md5('fitmaster.exercise.4')::uuid, 'Тяга штанги в наклоне', 'Упражнение на широчайшие', 'barbell', 'Наклон корпуса вперед, тянуть штангу к животу, сводя лопатки', true),
      (md5('fitmaster.exercise.5')::uuid, 'Жим штанги стоя (армейский)', 'Упражнение на плечи', 'barbell', 'Штанга на груди, выжать над головой, не прогибая поясницу', true),
      (md5('fitmaster.exercise.6')::uuid, 'Подтягивания широким хватом', 'Упражнение с собственным весом для спины', 'bodyweight', 'Повиснуть на перекладине, подтянуть грудь к перекладине, локти в стороны', true),
      (md5('fitmaster.exercise.7')::uuid, 'Отжимания от пола', 'Классическое упражнение на грудь и трицепс', 'bodyweight', 'Упор лежа, опустить грудь к полу, выпрямить руки', true),
      (md5('fitmaster.exercise.8')::uuid, 'Приседания с собственным весом', 'Упражнение для ног без отягощения', 'bodyweight', 'Ноги на ширине плеч, присесть до угла 90°, встать', true),
      (md5('fitmaster.exercise.9')::uuid, 'Выпады с гантелями', 'Упражнение на ноги и ягодицы', 'dumbbell', 'Сделать шаг вперед, опустить заднее колено к полу, вернуться', true),
      (md5('fitmaster.exercise.10')::uuid, 'Жим гантелей лежа', 'Альтернатива штанге для груди', 'dumbbell', 'Лежа на скамье, опустить гантели по бокам груди, выжать вверх', true),
      (md5('fitmaster.exercise.11')::uuid, 'Разведение гантелей в стороны', 'Упражнение на среднюю дельту', 'dumbbell', 'Стоя, гантели у бедер, поднять через стороны до уровня плеч', true),
      (md5('fitmaster.exercise.12')::uuid, 'Сгибание рук с гантелями (бицепс)', 'Изолированное упражнение на бицепс', 'dumbbell', 'Сидя или стоя, поднимать гантели к плечам, супинируя кисти', true),
      (md5('fitmaster.exercise.13')::uuid, 'Тяга верхнего блока к груди', 'Упражнение в тренажере для спины', 'cable', 'Сидя, взяться за рукоять, тянуть к верху груди, сводя лопатки', true),
      (md5('fitmaster.exercise.14')::uuid, 'Жим ногами в тренажере', 'Базовое упражнение на ноги', 'machine', 'Сидя в платформе, ноги на ширине плеч, выжать платформу', true),
      (md5('fitmaster.exercise.15')::uuid, 'Разгибание ног в тренажере', 'Изоляция квадрицепсов', 'machine', 'Сидя, зацепив голени за валики, разогнуть ноги в коленях', true),
      (md5('fitmaster.exercise.16')::uuid, 'Сгибание ног в тренажере лежа', 'Изоляция бицепса бедра', 'machine', 'Лежа на животе, согнуть ноги в коленях, подтягивая пятки к ягодицам', true),
      (md5('fitmaster.exercise.17')::uuid, 'Пуловер с гантелью', 'Упражнение на грудные и широчайшие', 'dumbbell', 'Лежа поперек скамьи, опустить гантель за голову, вернуть в исходное', true),
      (md5('fitmaster.exercise.18')::uuid, 'Французский жим со штангой лежа', 'Упражнение на трицепс', 'barbell', 'Лежа, узким хватом опустить штангу ко лбу, разгибая локти', true),
      (md5('fitmaster.exercise.19')::uuid, 'Скручивания на пресс лежа', 'Классическое упражнение на прямую мышцу живота', 'bodyweight', 'Лежа на спине, согнуть колени, поднять лопатки от пола', true),
      (md5('fitmaster.exercise.20')::uuid, 'Планка', 'Статическое упражнение на кор', 'bodyweight', 'Упор на предплечьях и носках, держать тело прямым', true),
      (md5('fitmaster.exercise.21')::uuid, 'Гиперэкстензия (в тренажере)', 'Укрепление разгибателей спины', 'machine', 'Лежа лицом вниз на римском стуле, согнуться и выпрямить спину', true),
      (md5('fitmaster.exercise.22')::uuid, 'Тяга гантели к поясу одной рукой', 'Упражнение на широчайшие', 'dumbbell', 'Упор рукой и коленом на скамью, другой рукой тянуть гантель к животу', true),
      (md5('fitmaster.exercise.23')::uuid, 'Подъем на носки стоя (в тренажере)', 'Икроножные мышцы', 'machine', 'Стоя, плечи под подушками, подняться на носки, опустить', true),
      (md5('fitmaster.exercise.24')::uuid, 'Жим гантелей сидя над головой', 'Альтернатива штанге для дельт', 'dumbbell', 'Сидя на скамье с опорой спины, выжать гантели вверх', true),
      (md5('fitmaster.exercise.25')::uuid, 'Подтягивания обратным хватом', 'Акцент на бицепс', 'bodyweight', 'Вис на перекладине хватом снизу, подтянуться подбородком выше', true),
      (md5('fitmaster.exercise.26')::uuid, 'Отжимания на брусьях', 'Упражнение на трицепс и грудь', 'bodyweight', 'Упор на брусьях, опуститься, согнув локти, выжаться', true),
      (md5('fitmaster.exercise.27')::uuid, 'Приседания с гантелью (goblet squat)', 'Вариант приседа с одной гантелью у груди', 'dumbbell', 'Держать гантель вертикально у груди, приседать', true),
      (md5('fitmaster.exercise.28')::uuid, 'Жим штанги на наклонной скамье', 'Акцент на верх груди', 'barbell', 'Лежа на скамье 30-45°, жим штанги к верху груди', true),
      (md5('fitmaster.exercise.29')::uuid, 'Тяга нижнего блока к поясу', 'Упражнение на спину в тренажере', 'cable', 'Сидя, ноги в упор, тянуть рукоять к животу', true),
      (md5('fitmaster.exercise.30')::uuid, 'Разведение гантелей лежа (флай)', 'Изолированное упражнение на грудные', 'dumbbell', 'Лежа на скамье, руки с гантелями в стороны, свести над грудью', true),
      (md5('fitmaster.exercise.31')::uuid, 'Шраги со штангой', 'Упражнение на трапеции', 'barbell', 'Стоя, штанга в опущенных руках, пожать плечами вверх', true),
      (md5('fitmaster.exercise.32')::uuid, 'Обратные гиперэкстензии', 'Разгибание бедер лежа на животе', 'machine', 'Лежа на скамье лицом вниз, поднимать прямые ноги вверх', true),
      (md5('fitmaster.exercise.33')::uuid, 'Скручивания на римском стуле', 'Для нижнего пресса и косых', 'machine', 'Сидя на наклонной скамье, зафиксировав ноги, опуститься и скрутиться', true),
      (md5('fitmaster.exercise.34')::uuid, 'Подъем ног в висе', 'Упражнение на пресс', 'bodyweight', 'Вис на перекладине, поднять прямые ноги до уровня пояса', true),
      (md5('fitmaster.exercise.35')::uuid, 'Жим ногами одной ногой', 'Устраняет дисбаланс', 'machine', 'В тренажере для жима ногами выжимать платформу одной ногой', true),
      (md5('fitmaster.exercise.36')::uuid, 'Молотковые сгибания с гантелями', 'На брахиалис и бицепс', 'dumbbell', 'Стоя, гантели нейтральным хватом, поднимать к плечам', true),
      (md5('fitmaster.exercise.37')::uuid, 'Жим Арнольда', 'Вариация жима гантелей для дельт', 'dumbbell', 'Сидя, гантели у плеч ладонями к себе, выжимая разворачивать наружу', true),
      (md5('fitmaster.exercise.38')::uuid, 'Тяга штанги к подбородку', 'Упражнение на дельты и трапеции', 'barbell', 'Стоя, узким хватом тянуть штангу к подбородку, локти в стороны', true),
      (md5('fitmaster.exercise.39')::uuid, 'Выпады назад с гантелями', 'Менее нагружает колени', 'dumbbell', 'Сделать шаг назад, опустить колено, вернуться', true),
      (md5('fitmaster.exercise.40')::uuid, 'Отжимания с колен', 'Облегченный вариант отжиманий', 'bodyweight', 'Упор на коленях и руках, опустить грудь к полу', true),
      (md5('fitmaster.exercise.41')::uuid, 'Тяга верхнего блока обратным хватом', 'Вариация для низа широчайших', 'cable', 'Сидя, хват снизу, тянуть к груди', true),
      (md5('fitmaster.exercise.42')::uuid, 'Жим гантелей на наклонной скамье', 'Акцент на верх груди с гантелями', 'dumbbell', 'Лежа на скамье 30°, жим гантелей от груди вверх', true),
      (md5('fitmaster.exercise.43')::uuid, 'Румынская тяга с гантелями', 'Упражнение на заднюю поверхность бедра', 'dumbbell', 'Стоя, наклон с прямыми ногами, гантели скользят по голеням', true),
      (md5('fitmaster.exercise.44')::uuid, 'Сведение рук в кроссовере (верхние блоки)', 'Изоляция нижней и средней части груди', 'cable', 'Стоя, взяться за рукояти верхних блоков, свести руки вниз', true),
      (md5('fitmaster.exercise.45')::uuid, 'Разведение гантелей в наклоне', 'Упражнение на заднюю дельту', 'dumbbell', 'Наклон корпуса до параллели, поднять гантели в стороны', true),
      (md5('fitmaster.exercise.46')::uuid, 'Приседания со штангой на груди (фронтальные)', 'Вариация с меньшей нагрузкой на поясницу', 'barbell', 'Штанга на передних дельтах, локти вверх, присесть', true),
      (md5('fitmaster.exercise.47')::uuid, 'Подъем ног лежа на скамье (скручивания обратные)', 'Акцент на нижний пресс', 'bodyweight', 'Лежа на скамье, согнув ноги, подтянуть колени к груди, приподнимая таз', true),
      (md5('fitmaster.exercise.48')::uuid, 'Сгибание рук со штангой (бицепс)', 'Классика на бицепс', 'barbell', 'Стоя, штанга прямым хватом, согнуть руки к плечам', true),
      (md5('fitmaster.exercise.49')::uuid, 'Разгибание рук на верхнем блоке (трицепс)', 'Изоляция трицепса', 'cable', 'Стоя лицом к блоку, тянуть рукоять вниз, разгибая руки', true),
      (md5('fitmaster.exercise.50')::uuid, 'Боковые выпады с гантелей', 'Упражнение на приводящие мышцы', 'dumbbell', 'Шаг в сторону, согнуть опорную ногу, другую выпрямить', true),
      (md5('fitmaster.exercise.51')::uuid, 'Бег на беговой дорожке', 'Кардио-упражнение для сжигания калорий', 'cardio', 'Установить комфортную скорость, бежать, сохраняя ровное дыхание, не держась за поручни', true),
      (md5('fitmaster.exercise.52')::uuid, 'Интервальный бег на дорожке', 'Чередование интенсивного бега и ходьбы', 'cardio', '1 минута бег в высоком темпе, 1 минута ходьба – повторять цикл', true),
      (md5('fitmaster.exercise.53')::uuid, 'Ходьба на беговой дорожке (наклон)', 'Ходьба с высоким наклоном для нагрузки на ягодицы', 'cardio', 'Установить наклон 5-15%, идти быстрым шагом, не наклоняясь корпусом вперёд', true),
      (md5('fitmaster.exercise.54')::uuid, 'Велотренажёр', 'Имитация езды на велосипеде', 'cardio', 'Сидя, регулировать сопротивление педалям, вращать равномерно, спина прямая', true),
      (md5('fitmaster.exercise.55')::uuid, 'Эллиптический тренажёр (Эллипс)', 'Имитация бега с плавным движением ног', 'cardio', 'Стоя, двигать ногами и руками синхронно, не отрывая стоп от педалей', true),
      (md5('fitmaster.exercise.56')::uuid, 'Гребной тренажёр', 'Кардио, задействующее более 80% мышц тела', 'cardio', 'Сидя, взяться за рукоять, выпрямить ноги, отклонить корпус назад, подтянуть рукоять к груди', true),
      (md5('fitmaster.exercise.57')::uuid, 'Степпер', 'Имитация подъёма по лестнице, акцент на ягодицы', 'cardio', 'Стоя на педалях, переносить вес с пятки на носок, сохраняя вертикальное положение', true),
      (md5('fitmaster.exercise.58')::uuid, 'Прыжки на скакалке', 'Высокоинтенсивное кардио, развивающее координацию', 'bodyweight', 'Прыгать на носках, вращая скакалку запястьями, колени слегка согнуты', true),
      (md5('fitmaster.exercise.59')::uuid, 'Отжимания с широкой постановкой рук', 'Вариация для смещения акцента на грудные мышцы', 'bodyweight', 'Руки шире плеч, локти смотрят в стороны, опустить грудь почти до пола', true),
      (md5('fitmaster.exercise.60')::uuid, 'Отжимания с узкой постановкой рук', 'Акцент на трицепс', 'bodyweight', 'Руки уже плеч, локти прижаты к корпусу, опускаться до касания грудью кистей', true),
      (md5('fitmaster.exercise.61')::uuid, 'Алмазные (бриллиантовые) отжимания', 'Максимально нагружает трицепсы', 'bodyweight', 'Пальцы рук образуют ромб (треугольник), локти скользят по рёбрам', true),
      (md5('fitmaster.exercise.62')::uuid, 'Отжимания на кулаках', 'Для укрепления запястий и ударной поверхности', 'bodyweight', 'Упор на кулаки, запястья прямые, техника как у классических отжиманий', true),
      (md5('fitmaster.exercise.63')::uuid, 'Отжимания с ногами на возвышении', 'Смещает акцент на верх грудных мышц', 'bodyweight', 'Ноги на скамье/платформе, голова ниже ног, опускать грудь к полу', true),
      (md5('fitmaster.exercise.64')::uuid, 'Отжимания с хлопком (плиометрика)', 'Взрывные отжимания для развития мощности', 'plyometric', 'Отжаться с силой, чтобы оторвать руки от пола, сделать хлопок и приземлиться', true),
      (md5('fitmaster.exercise.65')::uuid, 'Отжимания с колен', 'Облегчённый вариант для начинающих', 'bodyweight', 'Упор на коленях и руках, спина прямая, опускаться до касания грудью пола', true),
      (md5('fitmaster.exercise.66')::uuid, 'Отжимания от стены', 'Самый лёгкий вариант, для новичков и реабилитации', 'bodyweight', 'Встать лицом к стене на расстоянии шага, согнуть руки и коснуться грудью стены', true),
      (md5('fitmaster.exercise.67')::uuid, 'Индуистские отжимания (Дэнда)', 'Динамическое упражнение с движением по дуге', 'bodyweight', 'Из положения «собака мордой вниз» дугой опустить голову к полу и подняться вверх', true),
      (md5('fitmaster.exercise.68')::uuid, '«Молитва» (скручивания с верхнего блока)', 'Изолированная проработка верхней части пресса', 'cable', 'Стоя на коленях перед кроссовером, тянуть канатную рукоять вниз, скручивая корпус', true),
      (md5('fitmaster.exercise.69')::uuid, 'Скручивания лежа на полу', 'Классическое упражнение на пресс', 'bodyweight', 'Лёжа на спине, ноги согнуты, руки за головой, оторвать лопатки от пола', true),
      (md5('fitmaster.exercise.70')::uuid, 'Обратные скручивания', 'Акцент на нижнюю часть пресса', 'bodyweight', 'Лёжа на спине, поднять таз вверх, скручиваясь снизу, ноги вверх', true),
      (md5('fitmaster.exercise.71')::uuid, 'Подъём ног в висе на перекладине', 'Эффективное упражнение для нижнего пресса', 'bodyweight', 'Вис на турнике, поднять прямые ноги до уровня пояса, медленно опустить', true),
      (md5('fitmaster.exercise.72')::uuid, 'Боковые скручивания (на косые мышцы)', 'Проработка косых мышц живота', 'bodyweight', 'Лёжа на боку, выполнять скручивание, приводя локоть к тазу', true),
      (md5('fitmaster.exercise.73')::uuid, 'Скручивания на фитболе', 'Увеличенная амплитуда из-за мяча', 'bodyweight', 'Лечь спиной на фитбол, стопы на полу, выполнять скручивания', true),
      (md5('fitmaster.exercise.74')::uuid, 'Скручивания в тренажёре (римский стул)', 'С большим рабочим весом', 'machine', 'На наклонной скамье с фиксацией ног, скручиваться, не отрывая поясницу', true),
      (md5('fitmaster.exercise.75')::uuid, 'Подъём ног с фитболом', 'Акцент на нижний пресс', 'bodyweight', 'Лёжа на полу, зажать фитбол между ног, поднимать прямые ноги вверх', true),
      (md5('fitmaster.exercise.76')::uuid, '«Дровосек»', 'Упражнение для косых мышц в кроссовере', 'cable', 'В кроссовере тянуть рукоять по диагонали сверху вниз, имитируя удар топора', true),
      (md5('fitmaster.exercise.77')::uuid, 'Боковая планка', 'Статическое упражнение на косые мышцы', 'bodyweight', 'Упор на предплечье одной руки сбоку, держать тело прямым, не проваливая таз', true),
      (md5('fitmaster.exercise.78')::uuid, 'Складка (V-up)', 'Динамическое упражнение на весь пресс', 'bodyweight', 'Из положения лёжа одновременно поднять корпус и прямые ноги, коснуться руками стоп', true),
      (md5('fitmaster.exercise.79')::uuid, '«Велосипед»', 'Имитация езды на велосипеде лёжа', 'bodyweight', 'Лёжа на спине, поочерёдно приводить локоть к противоположному колену, выпрямляя другую ногу', true),
      (md5('fitmaster.exercise.80')::uuid, '«Ножницы»', 'Упражнение для нижнего пресса', 'bodyweight', 'Лёжа на спине, поднять прямые ноги на 30°, выполнять скрещивающиеся движения', true),
      (md5('fitmaster.exercise.81')::uuid, 'Бёрпи (Burpee)', 'Интенсивное комплексное упражнение', 'plyometric', 'Присед → упор лёжа → отжимание → выпрыгивание вверх с хлопком', true),
      (md5('fitmaster.exercise.82')::uuid, 'Приседания с выпрыгиванием', 'Взрывные прыжки из приседа', 'plyometric', 'Из глубокого приседа резко выпрыгнуть вверх, приземляться мягко', true),
      (md5('fitmaster.exercise.83')::uuid, 'Прыжки в длину с места', 'Максимально дальний прыжок для взрывной силы ног', 'plyometric', 'Присесть, махнуть руками, выпрыгнуть вперёд-вверх, приземлиться на обе ноги', true),
      (md5('fitmaster.exercise.84')::uuid, 'Прыжки на тумбу (Box Jumps)', 'Запрыгивание на устойчивую платформу', 'plyometric', 'Встать перед тумбой, присесть, взрывом запрыгнуть, мягко приземлиться', true),
      (md5('fitmaster.exercise.85')::uuid, 'Выпады с выпрыгиванием', 'Смена ног в прыжке из выпада', 'plyometric', 'Из выпада прыжком поменять ноги, приземлиться в выпад другой ногой', true),
      (md5('fitmaster.exercise.86')::uuid, 'Тяга штанги Т-грифа', 'Базовое упражнение для толщины спины', 'barbell', 'Упереть грудь в опору, взяться за рукояти, тянуть штангу к животу, сводя лопатки', true),
      (md5('fitmaster.exercise.87')::uuid, 'Жим штанги лежа узким хватом', 'Акцент на трицепс', 'barbell', 'Лёжа, хват уже плеч, опускать штангу к нижней части груди, локти прижаты', true),
      (md5('fitmaster.exercise.88')::uuid, 'Приседания Зерхера', 'Штанга удерживается в сгибе локтей спереди', 'barbell', 'Взять штангу на сгибы локтей, приседать с прямой спиной, корпус почти вертикально', true),
      (md5('fitmaster.exercise.89')::uuid, 'Сгибание рук на бицепс на скамье Скотта', 'Изолированное упражнение на бицепс', 'machine', 'Сесть за пюпитр, положить руки на подставку, сгибать штангу/гантели к плечам', true),
      (md5('fitmaster.exercise.90')::uuid, 'Разгибание рук на трицепс с канатом', 'Изолированное упражнение в кроссовере', 'cable', 'Взяться за канатную рукоять, локти прижаты, разгибать руки вниз, разводя концы каната', true),
      (md5('fitmaster.exercise.91')::uuid, 'Тяга гантели к поясу в наклоне (одной рукой)', 'Для толщины и детализации широчайших', 'dumbbell', 'Упор рукой и коленом на скамью, другой рукой тянуть гантель к животу', true),
      (md5('fitmaster.exercise.92')::uuid, 'Попеременный жим гантелей лежа', 'Для координации и баланса мышц', 'dumbbell', 'Лёжа, поочерёдно выжимать гантели, удерживая равновесие', true),
      (md5('fitmaster.exercise.93')::uuid, 'Наклоны со штангой на плечах («Доброе утро»)', 'Для задней поверхности бедра и поясницы', 'barbell', 'Штанга на плечах, ноги чуть согнуты, наклониться вперёд с прямой спиной до параллели с полом', true),
      (md5('fitmaster.exercise.94')::uuid, 'Приседания с гантелью у груди (Goblet Squat)', 'Технически простые приседания', 'dumbbell', 'Держать гантель вертикально у груди, локти вниз, приседать до комфортной глубины', true),
      (md5('fitmaster.exercise.95')::uuid, 'Отведение бедра в кроссовере', 'Изолированное упражнение для ягодиц', 'cable', 'Встать боком к тренажёру, закрепить тросик на лодыжке, отводить ногу в сторону', true),
      (md5('fitmaster.exercise.96')::uuid, 'Тяга верхнего блока к груди широким хватом', 'Для ширины спины', 'cable', 'Сидя, взять рукоять широким хватом, тянуть к верху груди, локти в стороны', true),
      (md5('fitmaster.exercise.97')::uuid, 'Тяга нижнего блока к поясу', 'Для толщины спины', 'cable', 'Сидя, упереться ногами, тянуть V-образную рукоять к животу, прогибаясь в спине', true),
      (md5('fitmaster.exercise.98')::uuid, 'Ходьба выпадами с гантелями', 'Динамические выпады для ног и выносливости', 'dumbbell', 'Взять гантели в руки, делать шаг вперёд в выпад, затем приставлять другую ногу и повторять', true),
      (md5('fitmaster.exercise.99')::uuid, 'Отжимания на брусьях с весом', 'Усложнённый вариант для трицепса и груди', 'bodyweight', 'Использовать пояс для отягощения, опускаться до прямого угла в локтях, выжиматься', true),
      (md5('fitmaster.exercise.100')::uuid, 'Становая тяга на прямых ногах (румынская) с гантелями', 'Для задней поверхности бедра', 'dumbbell', 'Держать гантели перед бёдрами, наклоняться с прямыми ногами (колени чуть согнуты), опуская гантели до середины голени', true);
  `);

  pgm.sql(`INSERT INTO exercise_metric_templates (id, exercise_id, metric_type, required, default_value, unit)
    VALUES
      (md5('fitmaster.exercise-metric-template.1.reps')::uuid, md5('fitmaster.exercise.1')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.1.weight')::uuid, md5('fitmaster.exercise.1')::uuid, 'weight', true, 80, 'kg'),
      (md5('fitmaster.exercise-metric-template.2.reps')::uuid, md5('fitmaster.exercise.2')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.2.weight')::uuid, md5('fitmaster.exercise.2')::uuid, 'weight', true, 60, 'kg'),
      (md5('fitmaster.exercise-metric-template.3.reps')::uuid, md5('fitmaster.exercise.3')::uuid, 'reps', true, 8, 'count'),
      (md5('fitmaster.exercise-metric-template.3.weight')::uuid, md5('fitmaster.exercise.3')::uuid, 'weight', true, 100, 'kg'),
      (md5('fitmaster.exercise-metric-template.4.reps')::uuid, md5('fitmaster.exercise.4')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.4.weight')::uuid, md5('fitmaster.exercise.4')::uuid, 'weight', true, 50, 'kg'),
      (md5('fitmaster.exercise-metric-template.5.reps')::uuid, md5('fitmaster.exercise.5')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.5.weight')::uuid, md5('fitmaster.exercise.5')::uuid, 'weight', true, 40, 'kg'),
      (md5('fitmaster.exercise-metric-template.6.reps')::uuid, md5('fitmaster.exercise.6')::uuid, 'reps', true, 8, 'count'),
      (md5('fitmaster.exercise-metric-template.7.reps')::uuid, md5('fitmaster.exercise.7')::uuid, 'reps', true, 15, 'count'),
      (md5('fitmaster.exercise-metric-template.8.reps')::uuid, md5('fitmaster.exercise.8')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.9.reps')::uuid, md5('fitmaster.exercise.9')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.9.weight')::uuid, md5('fitmaster.exercise.9')::uuid, 'weight', true, 20, 'kg'),
      (md5('fitmaster.exercise-metric-template.10.reps')::uuid, md5('fitmaster.exercise.10')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.10.weight')::uuid, md5('fitmaster.exercise.10')::uuid, 'weight', true, 40, 'kg'),
      (md5('fitmaster.exercise-metric-template.11.reps')::uuid, md5('fitmaster.exercise.11')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.11.weight')::uuid, md5('fitmaster.exercise.11')::uuid, 'weight', true, 10, 'kg'),
      (md5('fitmaster.exercise-metric-template.12.reps')::uuid, md5('fitmaster.exercise.12')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.12.weight')::uuid, md5('fitmaster.exercise.12')::uuid, 'weight', true, 12, 'kg'),
      (md5('fitmaster.exercise-metric-template.13.reps')::uuid, md5('fitmaster.exercise.13')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.13.weight')::uuid, md5('fitmaster.exercise.13')::uuid, 'weight', true, 45, 'kg'),
      (md5('fitmaster.exercise-metric-template.14.reps')::uuid, md5('fitmaster.exercise.14')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.14.weight')::uuid, md5('fitmaster.exercise.14')::uuid, 'weight', true, 80, 'kg'),
      (md5('fitmaster.exercise-metric-template.15.reps')::uuid, md5('fitmaster.exercise.15')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.15.weight')::uuid, md5('fitmaster.exercise.15')::uuid, 'weight', true, 30, 'kg'),
      (md5('fitmaster.exercise-metric-template.16.reps')::uuid, md5('fitmaster.exercise.16')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.16.weight')::uuid, md5('fitmaster.exercise.16')::uuid, 'weight', true, 30, 'kg'),
      (md5('fitmaster.exercise-metric-template.17.reps')::uuid, md5('fitmaster.exercise.17')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.17.weight')::uuid, md5('fitmaster.exercise.17')::uuid, 'weight', true, 20, 'kg'),
      (md5('fitmaster.exercise-metric-template.18.reps')::uuid, md5('fitmaster.exercise.18')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.18.weight')::uuid, md5('fitmaster.exercise.18')::uuid, 'weight', true, 25, 'kg'),
      (md5('fitmaster.exercise-metric-template.19.reps')::uuid, md5('fitmaster.exercise.19')::uuid, 'reps', true, 20, 'count'),
      (md5('fitmaster.exercise-metric-template.20.duration')::uuid, md5('fitmaster.exercise.20')::uuid, 'duration', true, 60, 'sec'),
      (md5('fitmaster.exercise-metric-template.21.reps')::uuid, md5('fitmaster.exercise.21')::uuid, 'reps', true, 15, 'count'),
      (md5('fitmaster.exercise-metric-template.22.reps')::uuid, md5('fitmaster.exercise.22')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.22.weight')::uuid, md5('fitmaster.exercise.22')::uuid, 'weight', true, 20, 'kg'),
      (md5('fitmaster.exercise-metric-template.23.reps')::uuid, md5('fitmaster.exercise.23')::uuid, 'reps', true, 15, 'count'),
      (md5('fitmaster.exercise-metric-template.23.weight')::uuid, md5('fitmaster.exercise.23')::uuid, 'weight', true, 50, 'kg'),
      (md5('fitmaster.exercise-metric-template.24.reps')::uuid, md5('fitmaster.exercise.24')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.24.weight')::uuid, md5('fitmaster.exercise.24')::uuid, 'weight', true, 20, 'kg'),
      (md5('fitmaster.exercise-metric-template.25.reps')::uuid, md5('fitmaster.exercise.25')::uuid, 'reps', true, 8, 'count'),
      (md5('fitmaster.exercise-metric-template.26.reps')::uuid, md5('fitmaster.exercise.26')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.27.reps')::uuid, md5('fitmaster.exercise.27')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.27.weight')::uuid, md5('fitmaster.exercise.27')::uuid, 'weight', true, 20, 'kg'),
      (md5('fitmaster.exercise-metric-template.28.reps')::uuid, md5('fitmaster.exercise.28')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.28.weight')::uuid, md5('fitmaster.exercise.28')::uuid, 'weight', true, 60, 'kg'),
      (md5('fitmaster.exercise-metric-template.29.reps')::uuid, md5('fitmaster.exercise.29')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.29.weight')::uuid, md5('fitmaster.exercise.29')::uuid, 'weight', true, 45, 'kg'),
      (md5('fitmaster.exercise-metric-template.30.reps')::uuid, md5('fitmaster.exercise.30')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.30.weight')::uuid, md5('fitmaster.exercise.30')::uuid, 'weight', true, 15, 'kg'),
      (md5('fitmaster.exercise-metric-template.31.reps')::uuid, md5('fitmaster.exercise.31')::uuid, 'reps', true, 15, 'count'),
      (md5('fitmaster.exercise-metric-template.31.weight')::uuid, md5('fitmaster.exercise.31')::uuid, 'weight', true, 60, 'kg'),
      (md5('fitmaster.exercise-metric-template.32.reps')::uuid, md5('fitmaster.exercise.32')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.33.reps')::uuid, md5('fitmaster.exercise.33')::uuid, 'reps', true, 20, 'count'),
      (md5('fitmaster.exercise-metric-template.34.reps')::uuid, md5('fitmaster.exercise.34')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.35.reps')::uuid, md5('fitmaster.exercise.35')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.35.weight')::uuid, md5('fitmaster.exercise.35')::uuid, 'weight', true, 60, 'kg'),
      (md5('fitmaster.exercise-metric-template.36.reps')::uuid, md5('fitmaster.exercise.36')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.36.weight')::uuid, md5('fitmaster.exercise.36')::uuid, 'weight', true, 12, 'kg'),
      (md5('fitmaster.exercise-metric-template.37.reps')::uuid, md5('fitmaster.exercise.37')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.37.weight')::uuid, md5('fitmaster.exercise.37')::uuid, 'weight', true, 15, 'kg'),
      (md5('fitmaster.exercise-metric-template.38.reps')::uuid, md5('fitmaster.exercise.38')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.38.weight')::uuid, md5('fitmaster.exercise.38')::uuid, 'weight', true, 30, 'kg'),
      (md5('fitmaster.exercise-metric-template.39.reps')::uuid, md5('fitmaster.exercise.39')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.39.weight')::uuid, md5('fitmaster.exercise.39')::uuid, 'weight', true, 20, 'kg'),
      (md5('fitmaster.exercise-metric-template.40.reps')::uuid, md5('fitmaster.exercise.40')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.41.reps')::uuid, md5('fitmaster.exercise.41')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.41.weight')::uuid, md5('fitmaster.exercise.41')::uuid, 'weight', true, 45, 'kg'),
      (md5('fitmaster.exercise-metric-template.42.reps')::uuid, md5('fitmaster.exercise.42')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.42.weight')::uuid, md5('fitmaster.exercise.42')::uuid, 'weight', true, 20, 'kg'),
      (md5('fitmaster.exercise-metric-template.43.reps')::uuid, md5('fitmaster.exercise.43')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.43.weight')::uuid, md5('fitmaster.exercise.43')::uuid, 'weight', true, 20, 'kg'),
      (md5('fitmaster.exercise-metric-template.44.reps')::uuid, md5('fitmaster.exercise.44')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.44.weight')::uuid, md5('fitmaster.exercise.44')::uuid, 'weight', true, 15, 'kg'),
      (md5('fitmaster.exercise-metric-template.45.reps')::uuid, md5('fitmaster.exercise.45')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.45.weight')::uuid, md5('fitmaster.exercise.45')::uuid, 'weight', true, 10, 'kg'),
      (md5('fitmaster.exercise-metric-template.46.reps')::uuid, md5('fitmaster.exercise.46')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.46.weight')::uuid, md5('fitmaster.exercise.46')::uuid, 'weight', true, 60, 'kg'),
      (md5('fitmaster.exercise-metric-template.47.reps')::uuid, md5('fitmaster.exercise.47')::uuid, 'reps', true, 15, 'count'),
      (md5('fitmaster.exercise-metric-template.48.reps')::uuid, md5('fitmaster.exercise.48')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.48.weight')::uuid, md5('fitmaster.exercise.48')::uuid, 'weight', true, 30, 'kg'),
      (md5('fitmaster.exercise-metric-template.49.reps')::uuid, md5('fitmaster.exercise.49')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.49.weight')::uuid, md5('fitmaster.exercise.49')::uuid, 'weight', true, 20, 'kg'),
      (md5('fitmaster.exercise-metric-template.50.reps')::uuid, md5('fitmaster.exercise.50')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.50.weight')::uuid, md5('fitmaster.exercise.50')::uuid, 'weight', true, 15, 'kg'),
      (md5('fitmaster.exercise-metric-template.51.duration')::uuid, md5('fitmaster.exercise.51')::uuid, 'duration', true, 20, 'min'),
      (md5('fitmaster.exercise-metric-template.51.distance')::uuid, md5('fitmaster.exercise.51')::uuid, 'distance', true, 3, 'km'),
      (md5('fitmaster.exercise-metric-template.52.duration')::uuid, md5('fitmaster.exercise.52')::uuid, 'duration', true, 20, 'min'),
      (md5('fitmaster.exercise-metric-template.52.distance')::uuid, md5('fitmaster.exercise.52')::uuid, 'distance', true, 3, 'km'),
      (md5('fitmaster.exercise-metric-template.53.duration')::uuid, md5('fitmaster.exercise.53')::uuid, 'duration', true, 20, 'min'),
      (md5('fitmaster.exercise-metric-template.53.distance')::uuid, md5('fitmaster.exercise.53')::uuid, 'distance', true, 2, 'km'),
      (md5('fitmaster.exercise-metric-template.54.duration')::uuid, md5('fitmaster.exercise.54')::uuid, 'duration', true, 20, 'min'),
      (md5('fitmaster.exercise-metric-template.54.distance')::uuid, md5('fitmaster.exercise.54')::uuid, 'distance', true, 5, 'km'),
      (md5('fitmaster.exercise-metric-template.55.duration')::uuid, md5('fitmaster.exercise.55')::uuid, 'duration', true, 20, 'min'),
      (md5('fitmaster.exercise-metric-template.55.distance')::uuid, md5('fitmaster.exercise.55')::uuid, 'distance', true, 3, 'km'),
      (md5('fitmaster.exercise-metric-template.56.duration')::uuid, md5('fitmaster.exercise.56')::uuid, 'duration', true, 15, 'min'),
      (md5('fitmaster.exercise-metric-template.56.distance')::uuid, md5('fitmaster.exercise.56')::uuid, 'distance', true, 3, 'km'),
      (md5('fitmaster.exercise-metric-template.57.duration')::uuid, md5('fitmaster.exercise.57')::uuid, 'duration', true, 15, 'min'),
      (md5('fitmaster.exercise-metric-template.57.distance')::uuid, md5('fitmaster.exercise.57')::uuid, 'distance', true, 1, 'km'),
      (md5('fitmaster.exercise-metric-template.58.duration')::uuid, md5('fitmaster.exercise.58')::uuid, 'duration', true, 1, 'min'),
      (md5('fitmaster.exercise-metric-template.58.reps')::uuid, md5('fitmaster.exercise.58')::uuid, 'reps', true, 100, 'count'),
      (md5('fitmaster.exercise-metric-template.59.reps')::uuid, md5('fitmaster.exercise.59')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.60.reps')::uuid, md5('fitmaster.exercise.60')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.61.reps')::uuid, md5('fitmaster.exercise.61')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.62.reps')::uuid, md5('fitmaster.exercise.62')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.63.reps')::uuid, md5('fitmaster.exercise.63')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.64.reps')::uuid, md5('fitmaster.exercise.64')::uuid, 'reps', true, 5, 'count'),
      (md5('fitmaster.exercise-metric-template.65.reps')::uuid, md5('fitmaster.exercise.65')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.66.reps')::uuid, md5('fitmaster.exercise.66')::uuid, 'reps', true, 15, 'count'),
      (md5('fitmaster.exercise-metric-template.67.reps')::uuid, md5('fitmaster.exercise.67')::uuid, 'reps', true, 8, 'count'),
      (md5('fitmaster.exercise-metric-template.68.reps')::uuid, md5('fitmaster.exercise.68')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.68.weight')::uuid, md5('fitmaster.exercise.68')::uuid, 'weight', true, 20, 'kg'),
      (md5('fitmaster.exercise-metric-template.69.reps')::uuid, md5('fitmaster.exercise.69')::uuid, 'reps', true, 20, 'count'),
      (md5('fitmaster.exercise-metric-template.70.reps')::uuid, md5('fitmaster.exercise.70')::uuid, 'reps', true, 15, 'count'),
      (md5('fitmaster.exercise-metric-template.71.reps')::uuid, md5('fitmaster.exercise.71')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.72.reps')::uuid, md5('fitmaster.exercise.72')::uuid, 'reps', true, 15, 'count'),
      (md5('fitmaster.exercise-metric-template.73.reps')::uuid, md5('fitmaster.exercise.73')::uuid, 'reps', true, 15, 'count'),
      (md5('fitmaster.exercise-metric-template.74.reps')::uuid, md5('fitmaster.exercise.74')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.74.weight')::uuid, md5('fitmaster.exercise.74')::uuid, 'weight', true, 10, 'kg'),
      (md5('fitmaster.exercise-metric-template.75.reps')::uuid, md5('fitmaster.exercise.75')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.76.reps')::uuid, md5('fitmaster.exercise.76')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.76.weight')::uuid, md5('fitmaster.exercise.76')::uuid, 'weight', true, 15, 'kg'),
      (md5('fitmaster.exercise-metric-template.77.duration')::uuid, md5('fitmaster.exercise.77')::uuid, 'duration', true, 30, 'sec'),
      (md5('fitmaster.exercise-metric-template.78.reps')::uuid, md5('fitmaster.exercise.78')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.79.reps')::uuid, md5('fitmaster.exercise.79')::uuid, 'reps', true, 20, 'count'),
      (md5('fitmaster.exercise-metric-template.79.duration')::uuid, md5('fitmaster.exercise.79')::uuid, 'duration', true, 30, 'sec'),
      (md5('fitmaster.exercise-metric-template.80.reps')::uuid, md5('fitmaster.exercise.80')::uuid, 'reps', true, 20, 'count'),
      (md5('fitmaster.exercise-metric-template.80.duration')::uuid, md5('fitmaster.exercise.80')::uuid, 'duration', true, 30, 'sec'),
      (md5('fitmaster.exercise-metric-template.81.reps')::uuid, md5('fitmaster.exercise.81')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.81.duration')::uuid, md5('fitmaster.exercise.81')::uuid, 'duration', true, 30, 'sec'),
      (md5('fitmaster.exercise-metric-template.82.reps')::uuid, md5('fitmaster.exercise.82')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.83.distance')::uuid, md5('fitmaster.exercise.83')::uuid, 'distance', true, 1.5, 'metr'),
      (md5('fitmaster.exercise-metric-template.84.reps')::uuid, md5('fitmaster.exercise.84')::uuid, 'reps', true, 8, 'count'),
      (md5('fitmaster.exercise-metric-template.85.reps')::uuid, md5('fitmaster.exercise.85')::uuid, 'reps', true, 8, 'count'),
      (md5('fitmaster.exercise-metric-template.86.reps')::uuid, md5('fitmaster.exercise.86')::uuid, 'reps', true, 8, 'count'),
      (md5('fitmaster.exercise-metric-template.86.weight')::uuid, md5('fitmaster.exercise.86')::uuid, 'weight', true, 60, 'kg'),
      (md5('fitmaster.exercise-metric-template.87.reps')::uuid, md5('fitmaster.exercise.87')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.87.weight')::uuid, md5('fitmaster.exercise.87')::uuid, 'weight', true, 50, 'kg'),
      (md5('fitmaster.exercise-metric-template.88.reps')::uuid, md5('fitmaster.exercise.88')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.88.weight')::uuid, md5('fitmaster.exercise.88')::uuid, 'weight', true, 60, 'kg'),
      (md5('fitmaster.exercise-metric-template.89.reps')::uuid, md5('fitmaster.exercise.89')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.89.weight')::uuid, md5('fitmaster.exercise.89')::uuid, 'weight', true, 20, 'kg'),
      (md5('fitmaster.exercise-metric-template.90.reps')::uuid, md5('fitmaster.exercise.90')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.90.weight')::uuid, md5('fitmaster.exercise.90')::uuid, 'weight', true, 15, 'kg'),
      (md5('fitmaster.exercise-metric-template.91.reps')::uuid, md5('fitmaster.exercise.91')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.91.weight')::uuid, md5('fitmaster.exercise.91')::uuid, 'weight', true, 20, 'kg'),
      (md5('fitmaster.exercise-metric-template.92.reps')::uuid, md5('fitmaster.exercise.92')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.92.weight')::uuid, md5('fitmaster.exercise.92')::uuid, 'weight', true, 20, 'kg'),
      (md5('fitmaster.exercise-metric-template.93.reps')::uuid, md5('fitmaster.exercise.93')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.93.weight')::uuid, md5('fitmaster.exercise.93')::uuid, 'weight', true, 40, 'kg'),
      (md5('fitmaster.exercise-metric-template.94.reps')::uuid, md5('fitmaster.exercise.94')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.94.weight')::uuid, md5('fitmaster.exercise.94')::uuid, 'weight', true, 20, 'kg'),
      (md5('fitmaster.exercise-metric-template.95.reps')::uuid, md5('fitmaster.exercise.95')::uuid, 'reps', true, 15, 'count'),
      (md5('fitmaster.exercise-metric-template.95.weight')::uuid, md5('fitmaster.exercise.95')::uuid, 'weight', true, 10, 'kg'),
      (md5('fitmaster.exercise-metric-template.96.reps')::uuid, md5('fitmaster.exercise.96')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.96.weight')::uuid, md5('fitmaster.exercise.96')::uuid, 'weight', true, 45, 'kg'),
      (md5('fitmaster.exercise-metric-template.97.reps')::uuid, md5('fitmaster.exercise.97')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.97.weight')::uuid, md5('fitmaster.exercise.97')::uuid, 'weight', true, 50, 'kg'),
      (md5('fitmaster.exercise-metric-template.98.reps')::uuid, md5('fitmaster.exercise.98')::uuid, 'reps', true, 10, 'count'),
      (md5('fitmaster.exercise-metric-template.98.weight')::uuid, md5('fitmaster.exercise.98')::uuid, 'weight', true, 15, 'kg'),
      (md5('fitmaster.exercise-metric-template.98.duration')::uuid, md5('fitmaster.exercise.98')::uuid, 'duration', false, NULL, 'min'),
      (md5('fitmaster.exercise-metric-template.99.reps')::uuid, md5('fitmaster.exercise.99')::uuid, 'reps', true, 8, 'count'),
      (md5('fitmaster.exercise-metric-template.99.weight')::uuid, md5('fitmaster.exercise.99')::uuid, 'weight', true, 10, 'kg'),
      (md5('fitmaster.exercise-metric-template.100.reps')::uuid, md5('fitmaster.exercise.100')::uuid, 'reps', true, 12, 'count'),
      (md5('fitmaster.exercise-metric-template.100.weight')::uuid, md5('fitmaster.exercise.100')::uuid, 'weight', true, 20, 'kg');
  `);

  // Индекс
  pgm.createIndex('exercise_metric_templates', ['exercise_id'], { name: 'idx_exercise_metric_templates_exercise_id' });

  // Триггер
  pgm.sql(`CREATE TRIGGER update_exercise_metric_templates_updated_at
    BEFORE UPDATE ON exercise_metric_templates
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  `);
}

export async function down(pgm: MigrationBuilder): Promise<void> {
  pgm.sql(`DROP TRIGGER IF EXISTS update_exercise_metric_templates_updated_at ON exercise_metric_templates;`);
  pgm.dropIndex('exercise_metric_templates', 'idx_exercise_metric_templates_exercise_id', { ifExists: true });

  pgm.sql(`
    DELETE FROM exercise_metric_templates WHERE exercise_id IN (
      md5('fitmaster.exercise.1')::uuid,
      md5('fitmaster.exercise.2')::uuid,
      md5('fitmaster.exercise.3')::uuid,
      md5('fitmaster.exercise.4')::uuid,
      md5('fitmaster.exercise.5')::uuid,
      md5('fitmaster.exercise.6')::uuid,
      md5('fitmaster.exercise.7')::uuid,
      md5('fitmaster.exercise.8')::uuid,
      md5('fitmaster.exercise.9')::uuid,
      md5('fitmaster.exercise.10')::uuid,
      md5('fitmaster.exercise.11')::uuid,
      md5('fitmaster.exercise.12')::uuid,
      md5('fitmaster.exercise.13')::uuid,
      md5('fitmaster.exercise.14')::uuid,
      md5('fitmaster.exercise.15')::uuid,
      md5('fitmaster.exercise.16')::uuid,
      md5('fitmaster.exercise.17')::uuid,
      md5('fitmaster.exercise.18')::uuid,
      md5('fitmaster.exercise.19')::uuid,
      md5('fitmaster.exercise.20')::uuid,
      md5('fitmaster.exercise.21')::uuid,
      md5('fitmaster.exercise.22')::uuid,
      md5('fitmaster.exercise.23')::uuid,
      md5('fitmaster.exercise.24')::uuid,
      md5('fitmaster.exercise.25')::uuid,
      md5('fitmaster.exercise.26')::uuid,
      md5('fitmaster.exercise.27')::uuid,
      md5('fitmaster.exercise.28')::uuid,
      md5('fitmaster.exercise.29')::uuid,
      md5('fitmaster.exercise.30')::uuid,
      md5('fitmaster.exercise.31')::uuid,
      md5('fitmaster.exercise.32')::uuid,
      md5('fitmaster.exercise.33')::uuid,
      md5('fitmaster.exercise.34')::uuid,
      md5('fitmaster.exercise.35')::uuid,
      md5('fitmaster.exercise.36')::uuid,
      md5('fitmaster.exercise.37')::uuid,
      md5('fitmaster.exercise.38')::uuid,
      md5('fitmaster.exercise.39')::uuid,
      md5('fitmaster.exercise.40')::uuid,
      md5('fitmaster.exercise.41')::uuid,
      md5('fitmaster.exercise.42')::uuid,
      md5('fitmaster.exercise.43')::uuid,
      md5('fitmaster.exercise.44')::uuid,
      md5('fitmaster.exercise.45')::uuid,
      md5('fitmaster.exercise.46')::uuid,
      md5('fitmaster.exercise.47')::uuid,
      md5('fitmaster.exercise.48')::uuid,
      md5('fitmaster.exercise.49')::uuid,
      md5('fitmaster.exercise.50')::uuid,
      md5('fitmaster.exercise.51')::uuid,
      md5('fitmaster.exercise.52')::uuid,
      md5('fitmaster.exercise.53')::uuid,
      md5('fitmaster.exercise.54')::uuid,
      md5('fitmaster.exercise.55')::uuid,
      md5('fitmaster.exercise.56')::uuid,
      md5('fitmaster.exercise.57')::uuid,
      md5('fitmaster.exercise.58')::uuid,
      md5('fitmaster.exercise.59')::uuid,
      md5('fitmaster.exercise.60')::uuid,
      md5('fitmaster.exercise.61')::uuid,
      md5('fitmaster.exercise.62')::uuid,
      md5('fitmaster.exercise.63')::uuid,
      md5('fitmaster.exercise.64')::uuid,
      md5('fitmaster.exercise.65')::uuid,
      md5('fitmaster.exercise.66')::uuid,
      md5('fitmaster.exercise.67')::uuid,
      md5('fitmaster.exercise.68')::uuid,
      md5('fitmaster.exercise.69')::uuid,
      md5('fitmaster.exercise.70')::uuid,
      md5('fitmaster.exercise.71')::uuid,
      md5('fitmaster.exercise.72')::uuid,
      md5('fitmaster.exercise.73')::uuid,
      md5('fitmaster.exercise.74')::uuid,
      md5('fitmaster.exercise.75')::uuid,
      md5('fitmaster.exercise.76')::uuid,
      md5('fitmaster.exercise.77')::uuid,
      md5('fitmaster.exercise.78')::uuid,
      md5('fitmaster.exercise.79')::uuid,
      md5('fitmaster.exercise.80')::uuid,
      md5('fitmaster.exercise.81')::uuid,
      md5('fitmaster.exercise.82')::uuid,
      md5('fitmaster.exercise.83')::uuid,
      md5('fitmaster.exercise.84')::uuid,
      md5('fitmaster.exercise.85')::uuid,
      md5('fitmaster.exercise.86')::uuid,
      md5('fitmaster.exercise.87')::uuid,
      md5('fitmaster.exercise.88')::uuid,
      md5('fitmaster.exercise.89')::uuid,
      md5('fitmaster.exercise.90')::uuid,
      md5('fitmaster.exercise.91')::uuid,
      md5('fitmaster.exercise.92')::uuid,
      md5('fitmaster.exercise.93')::uuid,
      md5('fitmaster.exercise.94')::uuid,
      md5('fitmaster.exercise.95')::uuid,
      md5('fitmaster.exercise.96')::uuid,
      md5('fitmaster.exercise.97')::uuid,
      md5('fitmaster.exercise.98')::uuid,
      md5('fitmaster.exercise.99')::uuid,
      md5('fitmaster.exercise.100')::uuid
    );

    DELETE FROM exercise_muscles WHERE exercise_id IN (md5('fitmaster.exercise.1')::uuid,md5('fitmaster.exercise.2')::uuid,md5('fitmaster.exercise.3')::uuid,md5('fitmaster.exercise.4')::uuid,md5('fitmaster.exercise.5')::uuid,md5('fitmaster.exercise.6')::uuid,md5('fitmaster.exercise.7')::uuid,md5('fitmaster.exercise.8')::uuid,md5('fitmaster.exercise.9')::uuid,md5('fitmaster.exercise.10')::uuid,md5('fitmaster.exercise.11')::uuid,md5('fitmaster.exercise.12')::uuid,md5('fitmaster.exercise.13')::uuid,md5('fitmaster.exercise.14')::uuid,md5('fitmaster.exercise.15')::uuid,md5('fitmaster.exercise.16')::uuid,md5('fitmaster.exercise.17')::uuid,md5('fitmaster.exercise.18')::uuid,md5('fitmaster.exercise.19')::uuid,md5('fitmaster.exercise.20')::uuid,md5('fitmaster.exercise.21')::uuid,md5('fitmaster.exercise.22')::uuid,md5('fitmaster.exercise.23')::uuid,md5('fitmaster.exercise.24')::uuid,md5('fitmaster.exercise.25')::uuid,md5('fitmaster.exercise.26')::uuid,md5('fitmaster.exercise.27')::uuid,md5('fitmaster.exercise.28')::uuid,md5('fitmaster.exercise.29')::uuid,md5('fitmaster.exercise.30')::uuid,md5('fitmaster.exercise.31')::uuid,md5('fitmaster.exercise.32')::uuid,md5('fitmaster.exercise.33')::uuid,md5('fitmaster.exercise.34')::uuid,md5('fitmaster.exercise.35')::uuid,md5('fitmaster.exercise.36')::uuid,md5('fitmaster.exercise.37')::uuid,md5('fitmaster.exercise.38')::uuid,md5('fitmaster.exercise.39')::uuid,md5('fitmaster.exercise.40')::uuid,md5('fitmaster.exercise.41')::uuid,md5('fitmaster.exercise.42')::uuid,md5('fitmaster.exercise.43')::uuid,md5('fitmaster.exercise.44')::uuid,md5('fitmaster.exercise.45')::uuid,md5('fitmaster.exercise.46')::uuid,md5('fitmaster.exercise.47')::uuid,md5('fitmaster.exercise.48')::uuid,md5('fitmaster.exercise.49')::uuid,md5('fitmaster.exercise.50')::uuid,md5('fitmaster.exercise.51')::uuid,md5('fitmaster.exercise.52')::uuid,md5('fitmaster.exercise.53')::uuid,md5('fitmaster.exercise.54')::uuid,md5('fitmaster.exercise.55')::uuid,md5('fitmaster.exercise.56')::uuid,md5('fitmaster.exercise.57')::uuid,md5('fitmaster.exercise.58')::uuid,md5('fitmaster.exercise.59')::uuid,md5('fitmaster.exercise.60')::uuid,md5('fitmaster.exercise.61')::uuid,md5('fitmaster.exercise.62')::uuid,md5('fitmaster.exercise.63')::uuid,md5('fitmaster.exercise.64')::uuid,md5('fitmaster.exercise.65')::uuid,md5('fitmaster.exercise.66')::uuid,md5('fitmaster.exercise.67')::uuid,md5('fitmaster.exercise.68')::uuid,md5('fitmaster.exercise.69')::uuid,md5('fitmaster.exercise.70')::uuid,md5('fitmaster.exercise.71')::uuid,md5('fitmaster.exercise.72')::uuid,md5('fitmaster.exercise.73')::uuid,md5('fitmaster.exercise.74')::uuid,md5('fitmaster.exercise.75')::uuid,md5('fitmaster.exercise.76')::uuid,md5('fitmaster.exercise.77')::uuid,md5('fitmaster.exercise.78')::uuid,md5('fitmaster.exercise.79')::uuid,md5('fitmaster.exercise.80')::uuid,md5('fitmaster.exercise.81')::uuid,md5('fitmaster.exercise.82')::uuid,md5('fitmaster.exercise.83')::uuid,md5('fitmaster.exercise.84')::uuid,md5('fitmaster.exercise.85')::uuid,md5('fitmaster.exercise.86')::uuid,md5('fitmaster.exercise.87')::uuid,md5('fitmaster.exercise.88')::uuid,md5('fitmaster.exercise.89')::uuid,md5('fitmaster.exercise.90')::uuid,md5('fitmaster.exercise.91')::uuid,md5('fitmaster.exercise.92')::uuid,md5('fitmaster.exercise.93')::uuid,md5('fitmaster.exercise.94')::uuid,md5('fitmaster.exercise.95')::uuid,md5('fitmaster.exercise.96')::uuid,md5('fitmaster.exercise.97')::uuid,md5('fitmaster.exercise.98')::uuid,md5('fitmaster.exercise.99')::uuid,md5('fitmaster.exercise.100')::uuid);

    DELETE FROM exercise_likes WHERE exercise_id IN (md5('fitmaster.exercise.1')::uuid,md5('fitmaster.exercise.2')::uuid,md5('fitmaster.exercise.3')::uuid,md5('fitmaster.exercise.4')::uuid,md5('fitmaster.exercise.5')::uuid,md5('fitmaster.exercise.6')::uuid,md5('fitmaster.exercise.7')::uuid,md5('fitmaster.exercise.8')::uuid,md5('fitmaster.exercise.9')::uuid,md5('fitmaster.exercise.10')::uuid,md5('fitmaster.exercise.11')::uuid,md5('fitmaster.exercise.12')::uuid,md5('fitmaster.exercise.13')::uuid,md5('fitmaster.exercise.14')::uuid,md5('fitmaster.exercise.15')::uuid,md5('fitmaster.exercise.16')::uuid,md5('fitmaster.exercise.17')::uuid,md5('fitmaster.exercise.18')::uuid,md5('fitmaster.exercise.19')::uuid,md5('fitmaster.exercise.20')::uuid,md5('fitmaster.exercise.21')::uuid,md5('fitmaster.exercise.22')::uuid,md5('fitmaster.exercise.23')::uuid,md5('fitmaster.exercise.24')::uuid,md5('fitmaster.exercise.25')::uuid,md5('fitmaster.exercise.26')::uuid,md5('fitmaster.exercise.27')::uuid,md5('fitmaster.exercise.28')::uuid,md5('fitmaster.exercise.29')::uuid,md5('fitmaster.exercise.30')::uuid,md5('fitmaster.exercise.31')::uuid,md5('fitmaster.exercise.32')::uuid,md5('fitmaster.exercise.33')::uuid,md5('fitmaster.exercise.34')::uuid,md5('fitmaster.exercise.35')::uuid,md5('fitmaster.exercise.36')::uuid,md5('fitmaster.exercise.37')::uuid,md5('fitmaster.exercise.38')::uuid,md5('fitmaster.exercise.39')::uuid,md5('fitmaster.exercise.40')::uuid,md5('fitmaster.exercise.41')::uuid,md5('fitmaster.exercise.42')::uuid,md5('fitmaster.exercise.43')::uuid,md5('fitmaster.exercise.44')::uuid,md5('fitmaster.exercise.45')::uuid,md5('fitmaster.exercise.46')::uuid,md5('fitmaster.exercise.47')::uuid,md5('fitmaster.exercise.48')::uuid,md5('fitmaster.exercise.49')::uuid,md5('fitmaster.exercise.50')::uuid,md5('fitmaster.exercise.51')::uuid,md5('fitmaster.exercise.52')::uuid,md5('fitmaster.exercise.53')::uuid,md5('fitmaster.exercise.54')::uuid,md5('fitmaster.exercise.55')::uuid,md5('fitmaster.exercise.56')::uuid,md5('fitmaster.exercise.57')::uuid,md5('fitmaster.exercise.58')::uuid,md5('fitmaster.exercise.59')::uuid,md5('fitmaster.exercise.60')::uuid,md5('fitmaster.exercise.61')::uuid,md5('fitmaster.exercise.62')::uuid,md5('fitmaster.exercise.63')::uuid,md5('fitmaster.exercise.64')::uuid,md5('fitmaster.exercise.65')::uuid,md5('fitmaster.exercise.66')::uuid,md5('fitmaster.exercise.67')::uuid,md5('fitmaster.exercise.68')::uuid,md5('fitmaster.exercise.69')::uuid,md5('fitmaster.exercise.70')::uuid,md5('fitmaster.exercise.71')::uuid,md5('fitmaster.exercise.72')::uuid,md5('fitmaster.exercise.73')::uuid,md5('fitmaster.exercise.74')::uuid,md5('fitmaster.exercise.75')::uuid,md5('fitmaster.exercise.76')::uuid,md5('fitmaster.exercise.77')::uuid,md5('fitmaster.exercise.78')::uuid,md5('fitmaster.exercise.79')::uuid,md5('fitmaster.exercise.80')::uuid,md5('fitmaster.exercise.81')::uuid,md5('fitmaster.exercise.82')::uuid,md5('fitmaster.exercise.83')::uuid,md5('fitmaster.exercise.84')::uuid,md5('fitmaster.exercise.85')::uuid,md5('fitmaster.exercise.86')::uuid,md5('fitmaster.exercise.87')::uuid,md5('fitmaster.exercise.88')::uuid,md5('fitmaster.exercise.89')::uuid,md5('fitmaster.exercise.90')::uuid,md5('fitmaster.exercise.91')::uuid,md5('fitmaster.exercise.92')::uuid,md5('fitmaster.exercise.93')::uuid,md5('fitmaster.exercise.94')::uuid,md5('fitmaster.exercise.95')::uuid,md5('fitmaster.exercise.96')::uuid,md5('fitmaster.exercise.97')::uuid,md5('fitmaster.exercise.98')::uuid,md5('fitmaster.exercise.99')::uuid,md5('fitmaster.exercise.100')::uuid);

    DELETE FROM exercise_substitutions WHERE exercise_id IN (md5('fitmaster.exercise.1')::uuid,md5('fitmaster.exercise.2')::uuid,md5('fitmaster.exercise.3')::uuid,md5('fitmaster.exercise.4')::uuid,md5('fitmaster.exercise.5')::uuid,md5('fitmaster.exercise.6')::uuid,md5('fitmaster.exercise.7')::uuid,md5('fitmaster.exercise.8')::uuid,md5('fitmaster.exercise.9')::uuid,md5('fitmaster.exercise.10')::uuid,md5('fitmaster.exercise.11')::uuid,md5('fitmaster.exercise.12')::uuid,md5('fitmaster.exercise.13')::uuid,md5('fitmaster.exercise.14')::uuid,md5('fitmaster.exercise.15')::uuid,md5('fitmaster.exercise.16')::uuid,md5('fitmaster.exercise.17')::uuid,md5('fitmaster.exercise.18')::uuid,md5('fitmaster.exercise.19')::uuid,md5('fitmaster.exercise.20')::uuid,md5('fitmaster.exercise.21')::uuid,md5('fitmaster.exercise.22')::uuid,md5('fitmaster.exercise.23')::uuid,md5('fitmaster.exercise.24')::uuid,md5('fitmaster.exercise.25')::uuid,md5('fitmaster.exercise.26')::uuid,md5('fitmaster.exercise.27')::uuid,md5('fitmaster.exercise.28')::uuid,md5('fitmaster.exercise.29')::uuid,md5('fitmaster.exercise.30')::uuid,md5('fitmaster.exercise.31')::uuid,md5('fitmaster.exercise.32')::uuid,md5('fitmaster.exercise.33')::uuid,md5('fitmaster.exercise.34')::uuid,md5('fitmaster.exercise.35')::uuid,md5('fitmaster.exercise.36')::uuid,md5('fitmaster.exercise.37')::uuid,md5('fitmaster.exercise.38')::uuid,md5('fitmaster.exercise.39')::uuid,md5('fitmaster.exercise.40')::uuid,md5('fitmaster.exercise.41')::uuid,md5('fitmaster.exercise.42')::uuid,md5('fitmaster.exercise.43')::uuid,md5('fitmaster.exercise.44')::uuid,md5('fitmaster.exercise.45')::uuid,md5('fitmaster.exercise.46')::uuid,md5('fitmaster.exercise.47')::uuid,md5('fitmaster.exercise.48')::uuid,md5('fitmaster.exercise.49')::uuid,md5('fitmaster.exercise.50')::uuid,md5('fitmaster.exercise.51')::uuid,md5('fitmaster.exercise.52')::uuid,md5('fitmaster.exercise.53')::uuid,md5('fitmaster.exercise.54')::uuid,md5('fitmaster.exercise.55')::uuid,md5('fitmaster.exercise.56')::uuid,md5('fitmaster.exercise.57')::uuid,md5('fitmaster.exercise.58')::uuid,md5('fitmaster.exercise.59')::uuid,md5('fitmaster.exercise.60')::uuid,md5('fitmaster.exercise.61')::uuid,md5('fitmaster.exercise.62')::uuid,md5('fitmaster.exercise.63')::uuid,md5('fitmaster.exercise.64')::uuid,md5('fitmaster.exercise.65')::uuid,md5('fitmaster.exercise.66')::uuid,md5('fitmaster.exercise.67')::uuid,md5('fitmaster.exercise.68')::uuid,md5('fitmaster.exercise.69')::uuid,md5('fitmaster.exercise.70')::uuid,md5('fitmaster.exercise.71')::uuid,md5('fitmaster.exercise.72')::uuid,md5('fitmaster.exercise.73')::uuid,md5('fitmaster.exercise.74')::uuid,md5('fitmaster.exercise.75')::uuid,md5('fitmaster.exercise.76')::uuid,md5('fitmaster.exercise.77')::uuid,md5('fitmaster.exercise.78')::uuid,md5('fitmaster.exercise.79')::uuid,md5('fitmaster.exercise.80')::uuid,md5('fitmaster.exercise.81')::uuid,md5('fitmaster.exercise.82')::uuid,md5('fitmaster.exercise.83')::uuid,md5('fitmaster.exercise.84')::uuid,md5('fitmaster.exercise.85')::uuid,md5('fitmaster.exercise.86')::uuid,md5('fitmaster.exercise.87')::uuid,md5('fitmaster.exercise.88')::uuid,md5('fitmaster.exercise.89')::uuid,md5('fitmaster.exercise.90')::uuid,md5('fitmaster.exercise.91')::uuid,md5('fitmaster.exercise.92')::uuid,md5('fitmaster.exercise.93')::uuid,md5('fitmaster.exercise.94')::uuid,md5('fitmaster.exercise.95')::uuid,md5('fitmaster.exercise.96')::uuid,md5('fitmaster.exercise.97')::uuid,md5('fitmaster.exercise.98')::uuid,md5('fitmaster.exercise.99')::uuid,md5('fitmaster.exercise.100')::uuid) OR substitute_exercise_id IN (md5('fitmaster.exercise.1')::uuid,md5('fitmaster.exercise.2')::uuid,md5('fitmaster.exercise.3')::uuid,md5('fitmaster.exercise.4')::uuid,md5('fitmaster.exercise.5')::uuid,md5('fitmaster.exercise.6')::uuid,md5('fitmaster.exercise.7')::uuid,md5('fitmaster.exercise.8')::uuid,md5('fitmaster.exercise.9')::uuid,md5('fitmaster.exercise.10')::uuid,md5('fitmaster.exercise.11')::uuid,md5('fitmaster.exercise.12')::uuid,md5('fitmaster.exercise.13')::uuid,md5('fitmaster.exercise.14')::uuid,md5('fitmaster.exercise.15')::uuid,md5('fitmaster.exercise.16')::uuid,md5('fitmaster.exercise.17')::uuid,md5('fitmaster.exercise.18')::uuid,md5('fitmaster.exercise.19')::uuid,md5('fitmaster.exercise.20')::uuid,md5('fitmaster.exercise.21')::uuid,md5('fitmaster.exercise.22')::uuid,md5('fitmaster.exercise.23')::uuid,md5('fitmaster.exercise.24')::uuid,md5('fitmaster.exercise.25')::uuid,md5('fitmaster.exercise.26')::uuid,md5('fitmaster.exercise.27')::uuid,md5('fitmaster.exercise.28')::uuid,md5('fitmaster.exercise.29')::uuid,md5('fitmaster.exercise.30')::uuid,md5('fitmaster.exercise.31')::uuid,md5('fitmaster.exercise.32')::uuid,md5('fitmaster.exercise.33')::uuid,md5('fitmaster.exercise.34')::uuid,md5('fitmaster.exercise.35')::uuid,md5('fitmaster.exercise.36')::uuid,md5('fitmaster.exercise.37')::uuid,md5('fitmaster.exercise.38')::uuid,md5('fitmaster.exercise.39')::uuid,md5('fitmaster.exercise.40')::uuid,md5('fitmaster.exercise.41')::uuid,md5('fitmaster.exercise.42')::uuid,md5('fitmaster.exercise.43')::uuid,md5('fitmaster.exercise.44')::uuid,md5('fitmaster.exercise.45')::uuid,md5('fitmaster.exercise.46')::uuid,md5('fitmaster.exercise.47')::uuid,md5('fitmaster.exercise.48')::uuid,md5('fitmaster.exercise.49')::uuid,md5('fitmaster.exercise.50')::uuid,md5('fitmaster.exercise.51')::uuid,md5('fitmaster.exercise.52')::uuid,md5('fitmaster.exercise.53')::uuid,md5('fitmaster.exercise.54')::uuid,md5('fitmaster.exercise.55')::uuid,md5('fitmaster.exercise.56')::uuid,md5('fitmaster.exercise.57')::uuid,md5('fitmaster.exercise.58')::uuid,md5('fitmaster.exercise.59')::uuid,md5('fitmaster.exercise.60')::uuid,md5('fitmaster.exercise.61')::uuid,md5('fitmaster.exercise.62')::uuid,md5('fitmaster.exercise.63')::uuid,md5('fitmaster.exercise.64')::uuid,md5('fitmaster.exercise.65')::uuid,md5('fitmaster.exercise.66')::uuid,md5('fitmaster.exercise.67')::uuid,md5('fitmaster.exercise.68')::uuid,md5('fitmaster.exercise.69')::uuid,md5('fitmaster.exercise.70')::uuid,md5('fitmaster.exercise.71')::uuid,md5('fitmaster.exercise.72')::uuid,md5('fitmaster.exercise.73')::uuid,md5('fitmaster.exercise.74')::uuid,md5('fitmaster.exercise.75')::uuid,md5('fitmaster.exercise.76')::uuid,md5('fitmaster.exercise.77')::uuid,md5('fitmaster.exercise.78')::uuid,md5('fitmaster.exercise.79')::uuid,md5('fitmaster.exercise.80')::uuid,md5('fitmaster.exercise.81')::uuid,md5('fitmaster.exercise.82')::uuid,md5('fitmaster.exercise.83')::uuid,md5('fitmaster.exercise.84')::uuid,md5('fitmaster.exercise.85')::uuid,md5('fitmaster.exercise.86')::uuid,md5('fitmaster.exercise.87')::uuid,md5('fitmaster.exercise.88')::uuid,md5('fitmaster.exercise.89')::uuid,md5('fitmaster.exercise.90')::uuid,md5('fitmaster.exercise.91')::uuid,md5('fitmaster.exercise.92')::uuid,md5('fitmaster.exercise.93')::uuid,md5('fitmaster.exercise.94')::uuid,md5('fitmaster.exercise.95')::uuid,md5('fitmaster.exercise.96')::uuid,md5('fitmaster.exercise.97')::uuid,md5('fitmaster.exercise.98')::uuid,md5('fitmaster.exercise.99')::uuid,md5('fitmaster.exercise.100')::uuid);

    DELETE FROM exercise_recommendations WHERE exercise_id IN (md5('fitmaster.exercise.1')::uuid,md5('fitmaster.exercise.2')::uuid,md5('fitmaster.exercise.3')::uuid,md5('fitmaster.exercise.4')::uuid,md5('fitmaster.exercise.5')::uuid,md5('fitmaster.exercise.6')::uuid,md5('fitmaster.exercise.7')::uuid,md5('fitmaster.exercise.8')::uuid,md5('fitmaster.exercise.9')::uuid,md5('fitmaster.exercise.10')::uuid,md5('fitmaster.exercise.11')::uuid,md5('fitmaster.exercise.12')::uuid,md5('fitmaster.exercise.13')::uuid,md5('fitmaster.exercise.14')::uuid,md5('fitmaster.exercise.15')::uuid,md5('fitmaster.exercise.16')::uuid,md5('fitmaster.exercise.17')::uuid,md5('fitmaster.exercise.18')::uuid,md5('fitmaster.exercise.19')::uuid,md5('fitmaster.exercise.20')::uuid,md5('fitmaster.exercise.21')::uuid,md5('fitmaster.exercise.22')::uuid,md5('fitmaster.exercise.23')::uuid,md5('fitmaster.exercise.24')::uuid,md5('fitmaster.exercise.25')::uuid,md5('fitmaster.exercise.26')::uuid,md5('fitmaster.exercise.27')::uuid,md5('fitmaster.exercise.28')::uuid,md5('fitmaster.exercise.29')::uuid,md5('fitmaster.exercise.30')::uuid,md5('fitmaster.exercise.31')::uuid,md5('fitmaster.exercise.32')::uuid,md5('fitmaster.exercise.33')::uuid,md5('fitmaster.exercise.34')::uuid,md5('fitmaster.exercise.35')::uuid,md5('fitmaster.exercise.36')::uuid,md5('fitmaster.exercise.37')::uuid,md5('fitmaster.exercise.38')::uuid,md5('fitmaster.exercise.39')::uuid,md5('fitmaster.exercise.40')::uuid,md5('fitmaster.exercise.41')::uuid,md5('fitmaster.exercise.42')::uuid,md5('fitmaster.exercise.43')::uuid,md5('fitmaster.exercise.44')::uuid,md5('fitmaster.exercise.45')::uuid,md5('fitmaster.exercise.46')::uuid,md5('fitmaster.exercise.47')::uuid,md5('fitmaster.exercise.48')::uuid,md5('fitmaster.exercise.49')::uuid,md5('fitmaster.exercise.50')::uuid,md5('fitmaster.exercise.51')::uuid,md5('fitmaster.exercise.52')::uuid,md5('fitmaster.exercise.53')::uuid,md5('fitmaster.exercise.54')::uuid,md5('fitmaster.exercise.55')::uuid,md5('fitmaster.exercise.56')::uuid,md5('fitmaster.exercise.57')::uuid,md5('fitmaster.exercise.58')::uuid,md5('fitmaster.exercise.59')::uuid,md5('fitmaster.exercise.60')::uuid,md5('fitmaster.exercise.61')::uuid,md5('fitmaster.exercise.62')::uuid,md5('fitmaster.exercise.63')::uuid,md5('fitmaster.exercise.64')::uuid,md5('fitmaster.exercise.65')::uuid,md5('fitmaster.exercise.66')::uuid,md5('fitmaster.exercise.67')::uuid,md5('fitmaster.exercise.68')::uuid,md5('fitmaster.exercise.69')::uuid,md5('fitmaster.exercise.70')::uuid,md5('fitmaster.exercise.71')::uuid,md5('fitmaster.exercise.72')::uuid,md5('fitmaster.exercise.73')::uuid,md5('fitmaster.exercise.74')::uuid,md5('fitmaster.exercise.75')::uuid,md5('fitmaster.exercise.76')::uuid,md5('fitmaster.exercise.77')::uuid,md5('fitmaster.exercise.78')::uuid,md5('fitmaster.exercise.79')::uuid,md5('fitmaster.exercise.80')::uuid,md5('fitmaster.exercise.81')::uuid,md5('fitmaster.exercise.82')::uuid,md5('fitmaster.exercise.83')::uuid,md5('fitmaster.exercise.84')::uuid,md5('fitmaster.exercise.85')::uuid,md5('fitmaster.exercise.86')::uuid,md5('fitmaster.exercise.87')::uuid,md5('fitmaster.exercise.88')::uuid,md5('fitmaster.exercise.89')::uuid,md5('fitmaster.exercise.90')::uuid,md5('fitmaster.exercise.91')::uuid,md5('fitmaster.exercise.92')::uuid,md5('fitmaster.exercise.93')::uuid,md5('fitmaster.exercise.94')::uuid,md5('fitmaster.exercise.95')::uuid,md5('fitmaster.exercise.96')::uuid,md5('fitmaster.exercise.97')::uuid,md5('fitmaster.exercise.98')::uuid,md5('fitmaster.exercise.99')::uuid,md5('fitmaster.exercise.100')::uuid) OR suggested_exercise_id IN (md5('fitmaster.exercise.1')::uuid,md5('fitmaster.exercise.2')::uuid,md5('fitmaster.exercise.3')::uuid,md5('fitmaster.exercise.4')::uuid,md5('fitmaster.exercise.5')::uuid,md5('fitmaster.exercise.6')::uuid,md5('fitmaster.exercise.7')::uuid,md5('fitmaster.exercise.8')::uuid,md5('fitmaster.exercise.9')::uuid,md5('fitmaster.exercise.10')::uuid,md5('fitmaster.exercise.11')::uuid,md5('fitmaster.exercise.12')::uuid,md5('fitmaster.exercise.13')::uuid,md5('fitmaster.exercise.14')::uuid,md5('fitmaster.exercise.15')::uuid,md5('fitmaster.exercise.16')::uuid,md5('fitmaster.exercise.17')::uuid,md5('fitmaster.exercise.18')::uuid,md5('fitmaster.exercise.19')::uuid,md5('fitmaster.exercise.20')::uuid,md5('fitmaster.exercise.21')::uuid,md5('fitmaster.exercise.22')::uuid,md5('fitmaster.exercise.23')::uuid,md5('fitmaster.exercise.24')::uuid,md5('fitmaster.exercise.25')::uuid,md5('fitmaster.exercise.26')::uuid,md5('fitmaster.exercise.27')::uuid,md5('fitmaster.exercise.28')::uuid,md5('fitmaster.exercise.29')::uuid,md5('fitmaster.exercise.30')::uuid,md5('fitmaster.exercise.31')::uuid,md5('fitmaster.exercise.32')::uuid,md5('fitmaster.exercise.33')::uuid,md5('fitmaster.exercise.34')::uuid,md5('fitmaster.exercise.35')::uuid,md5('fitmaster.exercise.36')::uuid,md5('fitmaster.exercise.37')::uuid,md5('fitmaster.exercise.38')::uuid,md5('fitmaster.exercise.39')::uuid,md5('fitmaster.exercise.40')::uuid,md5('fitmaster.exercise.41')::uuid,md5('fitmaster.exercise.42')::uuid,md5('fitmaster.exercise.43')::uuid,md5('fitmaster.exercise.44')::uuid,md5('fitmaster.exercise.45')::uuid,md5('fitmaster.exercise.46')::uuid,md5('fitmaster.exercise.47')::uuid,md5('fitmaster.exercise.48')::uuid,md5('fitmaster.exercise.49')::uuid,md5('fitmaster.exercise.50')::uuid,md5('fitmaster.exercise.51')::uuid,md5('fitmaster.exercise.52')::uuid,md5('fitmaster.exercise.53')::uuid,md5('fitmaster.exercise.54')::uuid,md5('fitmaster.exercise.55')::uuid,md5('fitmaster.exercise.56')::uuid,md5('fitmaster.exercise.57')::uuid,md5('fitmaster.exercise.58')::uuid,md5('fitmaster.exercise.59')::uuid,md5('fitmaster.exercise.60')::uuid,md5('fitmaster.exercise.61')::uuid,md5('fitmaster.exercise.62')::uuid,md5('fitmaster.exercise.63')::uuid,md5('fitmaster.exercise.64')::uuid,md5('fitmaster.exercise.65')::uuid,md5('fitmaster.exercise.66')::uuid,md5('fitmaster.exercise.67')::uuid,md5('fitmaster.exercise.68')::uuid,md5('fitmaster.exercise.69')::uuid,md5('fitmaster.exercise.70')::uuid,md5('fitmaster.exercise.71')::uuid,md5('fitmaster.exercise.72')::uuid,md5('fitmaster.exercise.73')::uuid,md5('fitmaster.exercise.74')::uuid,md5('fitmaster.exercise.75')::uuid,md5('fitmaster.exercise.76')::uuid,md5('fitmaster.exercise.77')::uuid,md5('fitmaster.exercise.78')::uuid,md5('fitmaster.exercise.79')::uuid,md5('fitmaster.exercise.80')::uuid,md5('fitmaster.exercise.81')::uuid,md5('fitmaster.exercise.82')::uuid,md5('fitmaster.exercise.83')::uuid,md5('fitmaster.exercise.84')::uuid,md5('fitmaster.exercise.85')::uuid,md5('fitmaster.exercise.86')::uuid,md5('fitmaster.exercise.87')::uuid,md5('fitmaster.exercise.88')::uuid,md5('fitmaster.exercise.89')::uuid,md5('fitmaster.exercise.90')::uuid,md5('fitmaster.exercise.91')::uuid,md5('fitmaster.exercise.92')::uuid,md5('fitmaster.exercise.93')::uuid,md5('fitmaster.exercise.94')::uuid,md5('fitmaster.exercise.95')::uuid,md5('fitmaster.exercise.96')::uuid,md5('fitmaster.exercise.97')::uuid,md5('fitmaster.exercise.98')::uuid,md5('fitmaster.exercise.99')::uuid,md5('fitmaster.exercise.100')::uuid);

    UPDATE user_workouts SET last_completed_exercise_id = NULL WHERE last_completed_exercise_id IN (md5('fitmaster.exercise.1')::uuid,md5('fitmaster.exercise.2')::uuid,md5('fitmaster.exercise.3')::uuid,md5('fitmaster.exercise.4')::uuid,md5('fitmaster.exercise.5')::uuid,md5('fitmaster.exercise.6')::uuid,md5('fitmaster.exercise.7')::uuid,md5('fitmaster.exercise.8')::uuid,md5('fitmaster.exercise.9')::uuid,md5('fitmaster.exercise.10')::uuid,md5('fitmaster.exercise.11')::uuid,md5('fitmaster.exercise.12')::uuid,md5('fitmaster.exercise.13')::uuid,md5('fitmaster.exercise.14')::uuid,md5('fitmaster.exercise.15')::uuid,md5('fitmaster.exercise.16')::uuid,md5('fitmaster.exercise.17')::uuid,md5('fitmaster.exercise.18')::uuid,md5('fitmaster.exercise.19')::uuid,md5('fitmaster.exercise.20')::uuid,md5('fitmaster.exercise.21')::uuid,md5('fitmaster.exercise.22')::uuid,md5('fitmaster.exercise.23')::uuid,md5('fitmaster.exercise.24')::uuid,md5('fitmaster.exercise.25')::uuid,md5('fitmaster.exercise.26')::uuid,md5('fitmaster.exercise.27')::uuid,md5('fitmaster.exercise.28')::uuid,md5('fitmaster.exercise.29')::uuid,md5('fitmaster.exercise.30')::uuid,md5('fitmaster.exercise.31')::uuid,md5('fitmaster.exercise.32')::uuid,md5('fitmaster.exercise.33')::uuid,md5('fitmaster.exercise.34')::uuid,md5('fitmaster.exercise.35')::uuid,md5('fitmaster.exercise.36')::uuid,md5('fitmaster.exercise.37')::uuid,md5('fitmaster.exercise.38')::uuid,md5('fitmaster.exercise.39')::uuid,md5('fitmaster.exercise.40')::uuid,md5('fitmaster.exercise.41')::uuid,md5('fitmaster.exercise.42')::uuid,md5('fitmaster.exercise.43')::uuid,md5('fitmaster.exercise.44')::uuid,md5('fitmaster.exercise.45')::uuid,md5('fitmaster.exercise.46')::uuid,md5('fitmaster.exercise.47')::uuid,md5('fitmaster.exercise.48')::uuid,md5('fitmaster.exercise.49')::uuid,md5('fitmaster.exercise.50')::uuid,md5('fitmaster.exercise.51')::uuid,md5('fitmaster.exercise.52')::uuid,md5('fitmaster.exercise.53')::uuid,md5('fitmaster.exercise.54')::uuid,md5('fitmaster.exercise.55')::uuid,md5('fitmaster.exercise.56')::uuid,md5('fitmaster.exercise.57')::uuid,md5('fitmaster.exercise.58')::uuid,md5('fitmaster.exercise.59')::uuid,md5('fitmaster.exercise.60')::uuid,md5('fitmaster.exercise.61')::uuid,md5('fitmaster.exercise.62')::uuid,md5('fitmaster.exercise.63')::uuid,md5('fitmaster.exercise.64')::uuid,md5('fitmaster.exercise.65')::uuid,md5('fitmaster.exercise.66')::uuid,md5('fitmaster.exercise.67')::uuid,md5('fitmaster.exercise.68')::uuid,md5('fitmaster.exercise.69')::uuid,md5('fitmaster.exercise.70')::uuid,md5('fitmaster.exercise.71')::uuid,md5('fitmaster.exercise.72')::uuid,md5('fitmaster.exercise.73')::uuid,md5('fitmaster.exercise.74')::uuid,md5('fitmaster.exercise.75')::uuid,md5('fitmaster.exercise.76')::uuid,md5('fitmaster.exercise.77')::uuid,md5('fitmaster.exercise.78')::uuid,md5('fitmaster.exercise.79')::uuid,md5('fitmaster.exercise.80')::uuid,md5('fitmaster.exercise.81')::uuid,md5('fitmaster.exercise.82')::uuid,md5('fitmaster.exercise.83')::uuid,md5('fitmaster.exercise.84')::uuid,md5('fitmaster.exercise.85')::uuid,md5('fitmaster.exercise.86')::uuid,md5('fitmaster.exercise.87')::uuid,md5('fitmaster.exercise.88')::uuid,md5('fitmaster.exercise.89')::uuid,md5('fitmaster.exercise.90')::uuid,md5('fitmaster.exercise.91')::uuid,md5('fitmaster.exercise.92')::uuid,md5('fitmaster.exercise.93')::uuid,md5('fitmaster.exercise.94')::uuid,md5('fitmaster.exercise.95')::uuid,md5('fitmaster.exercise.96')::uuid,md5('fitmaster.exercise.97')::uuid,md5('fitmaster.exercise.98')::uuid,md5('fitmaster.exercise.99')::uuid,md5('fitmaster.exercise.100')::uuid);

    DELETE FROM exercises WHERE id IN (
      md5('fitmaster.exercise.1')::uuid,
      md5('fitmaster.exercise.2')::uuid,
      md5('fitmaster.exercise.3')::uuid,
      md5('fitmaster.exercise.4')::uuid,
      md5('fitmaster.exercise.5')::uuid,
      md5('fitmaster.exercise.6')::uuid,
      md5('fitmaster.exercise.7')::uuid,
      md5('fitmaster.exercise.8')::uuid,
      md5('fitmaster.exercise.9')::uuid,
      md5('fitmaster.exercise.10')::uuid,
      md5('fitmaster.exercise.11')::uuid,
      md5('fitmaster.exercise.12')::uuid,
      md5('fitmaster.exercise.13')::uuid,
      md5('fitmaster.exercise.14')::uuid,
      md5('fitmaster.exercise.15')::uuid,
      md5('fitmaster.exercise.16')::uuid,
      md5('fitmaster.exercise.17')::uuid,
      md5('fitmaster.exercise.18')::uuid,
      md5('fitmaster.exercise.19')::uuid,
      md5('fitmaster.exercise.20')::uuid,
      md5('fitmaster.exercise.21')::uuid,
      md5('fitmaster.exercise.22')::uuid,
      md5('fitmaster.exercise.23')::uuid,
      md5('fitmaster.exercise.24')::uuid,
      md5('fitmaster.exercise.25')::uuid,
      md5('fitmaster.exercise.26')::uuid,
      md5('fitmaster.exercise.27')::uuid,
      md5('fitmaster.exercise.28')::uuid,
      md5('fitmaster.exercise.29')::uuid,
      md5('fitmaster.exercise.30')::uuid,
      md5('fitmaster.exercise.31')::uuid,
      md5('fitmaster.exercise.32')::uuid,
      md5('fitmaster.exercise.33')::uuid,
      md5('fitmaster.exercise.34')::uuid,
      md5('fitmaster.exercise.35')::uuid,
      md5('fitmaster.exercise.36')::uuid,
      md5('fitmaster.exercise.37')::uuid,
      md5('fitmaster.exercise.38')::uuid,
      md5('fitmaster.exercise.39')::uuid,
      md5('fitmaster.exercise.40')::uuid,
      md5('fitmaster.exercise.41')::uuid,
      md5('fitmaster.exercise.42')::uuid,
      md5('fitmaster.exercise.43')::uuid,
      md5('fitmaster.exercise.44')::uuid,
      md5('fitmaster.exercise.45')::uuid,
      md5('fitmaster.exercise.46')::uuid,
      md5('fitmaster.exercise.47')::uuid,
      md5('fitmaster.exercise.48')::uuid,
      md5('fitmaster.exercise.49')::uuid,
      md5('fitmaster.exercise.50')::uuid,
      md5('fitmaster.exercise.51')::uuid,
      md5('fitmaster.exercise.52')::uuid,
      md5('fitmaster.exercise.53')::uuid,
      md5('fitmaster.exercise.54')::uuid,
      md5('fitmaster.exercise.55')::uuid,
      md5('fitmaster.exercise.56')::uuid,
      md5('fitmaster.exercise.57')::uuid,
      md5('fitmaster.exercise.58')::uuid,
      md5('fitmaster.exercise.59')::uuid,
      md5('fitmaster.exercise.60')::uuid,
      md5('fitmaster.exercise.61')::uuid,
      md5('fitmaster.exercise.62')::uuid,
      md5('fitmaster.exercise.63')::uuid,
      md5('fitmaster.exercise.64')::uuid,
      md5('fitmaster.exercise.65')::uuid,
      md5('fitmaster.exercise.66')::uuid,
      md5('fitmaster.exercise.67')::uuid,
      md5('fitmaster.exercise.68')::uuid,
      md5('fitmaster.exercise.69')::uuid,
      md5('fitmaster.exercise.70')::uuid,
      md5('fitmaster.exercise.71')::uuid,
      md5('fitmaster.exercise.72')::uuid,
      md5('fitmaster.exercise.73')::uuid,
      md5('fitmaster.exercise.74')::uuid,
      md5('fitmaster.exercise.75')::uuid,
      md5('fitmaster.exercise.76')::uuid,
      md5('fitmaster.exercise.77')::uuid,
      md5('fitmaster.exercise.78')::uuid,
      md5('fitmaster.exercise.79')::uuid,
      md5('fitmaster.exercise.80')::uuid,
      md5('fitmaster.exercise.81')::uuid,
      md5('fitmaster.exercise.82')::uuid,
      md5('fitmaster.exercise.83')::uuid,
      md5('fitmaster.exercise.84')::uuid,
      md5('fitmaster.exercise.85')::uuid,
      md5('fitmaster.exercise.86')::uuid,
      md5('fitmaster.exercise.87')::uuid,
      md5('fitmaster.exercise.88')::uuid,
      md5('fitmaster.exercise.89')::uuid,
      md5('fitmaster.exercise.90')::uuid,
      md5('fitmaster.exercise.91')::uuid,
      md5('fitmaster.exercise.92')::uuid,
      md5('fitmaster.exercise.93')::uuid,
      md5('fitmaster.exercise.94')::uuid,
      md5('fitmaster.exercise.95')::uuid,
      md5('fitmaster.exercise.96')::uuid,
      md5('fitmaster.exercise.97')::uuid,
      md5('fitmaster.exercise.98')::uuid,
      md5('fitmaster.exercise.99')::uuid,
      md5('fitmaster.exercise.100')::uuid
    );
  `);
  
  pgm.dropColumn('exercises', 'verbal_instruction');
  pgm.dropTable('exercise_metric_templates', { ifExists: true, cascade: true });
}