import { ColumnDefinitions, MigrationBuilder } from 'node-pg-migrate';

export const shorthands: ColumnDefinitions | undefined = undefined;

export async function up(pgm: MigrationBuilder): Promise<void> {
     // 1. Создаём таблицы через SQL (чтобы использовать GENERATED BY DEFAULT AS IDENTITY)
  pgm.sql(`
    CREATE TABLE user_profiles (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
      first_name VARCHAR(50) NOT NULL,
      last_name VARCHAR(50) NOT NULL,
      birth_date DATE NOT NULL CHECK (birth_date <= CURRENT_DATE),
      gender gender_type NOT NULL DEFAULT 'male',
      height INTEGER NOT NULL CHECK (height > 100 AND height < 250),
      weight DECIMAL(5,2) NOT NULL CHECK (weight > 30 AND weight < 300),
      avatar_url TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE user_settings (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
      preferred_workout_time TIME DEFAULT '17:00:00',
      preferred_days INTEGER[] DEFAULT '{}',
      settings_json JSONB DEFAULT '{}',
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE user_preferences (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
      experience_level level DEFAULT 'novice',
      fitness_goal goal DEFAULT 'maintenance',
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

  `);

  // 2. Перенос данных из users
  pgm.sql(`
    INSERT INTO user_profiles (user_id, first_name, last_name, birth_date, gender, height, weight, avatar_url)
    SELECT id, first_name, last_name, birth_date, gender, height, weight, avatar_url FROM users;

    INSERT INTO user_settings (user_id, preferred_workout_time, preferred_days)
    SELECT id, preferred_workout_time, preferred_days FROM users;

    INSERT INTO user_preferences (user_id, experience_level, fitness_goal)
    SELECT id, experience_level, fitness_goal FROM users;
  `);

  // 3. Удаляем колонки из users
  pgm.dropColumn('users', 'first_name');
  pgm.dropColumn('users', 'last_name');
  pgm.dropColumn('users', 'birth_date');
  pgm.dropColumn('users', 'gender');
  pgm.dropColumn('users', 'height');
  pgm.dropColumn('users', 'weight');
  pgm.dropColumn('users', 'avatar_url');
  pgm.dropColumn('users', 'preferred_workout_time');
  pgm.dropColumn('users', 'preferred_days');
  pgm.dropColumn('users', 'experience_level');
  pgm.dropColumn('users', 'fitness_goal');

  // 4. Добавляем триггеры updated_at для новых таблиц
  pgm.sql(`
    CREATE TRIGGER update_user_profiles_updated_at BEFORE UPDATE ON user_profiles
      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

    CREATE TRIGGER update_user_settings_updated_at BEFORE UPDATE ON user_settings
      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

    CREATE TRIGGER update_user_preferences_updated_at BEFORE UPDATE ON user_preferences
      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  `);
}

export async function down(pgm: MigrationBuilder): Promise<void> {
     // 1. Восстанавливаем колонки в users (без NOT NULL, чтобы можно было вставить NULL, если данных нет)
  pgm.addColumn('users', {
    first_name: { type: 'varchar(50)' },
    last_name: { type: 'varchar(50)' },
    birth_date: { type: 'date' },
    gender: { type: 'gender_type', default: 'male' },
    height: { type: 'integer' },
    weight: { type: 'decimal(5,2)' },
    avatar_url: { type: 'text' },
    preferred_workout_time: { type: 'time', default: '17:00:00' },
    preferred_days: { type: 'integer[]', default: '{}' },
    experience_level: { type: 'level', default: 'novice' },
    fitness_goal: { type: 'goal', default: 'maintenance' }
  });

  // 2. Переносим данные обратно (если нужно) – но для простоты опускаем,
  // так как в разработке можно пересоздать БД. При необходимости можно дописать UPDATE с JOIN.

  // 3. Удаляем новые таблицы
  pgm.sql(`
    DROP TABLE IF EXISTS user_preferences CASCADE;
    DROP TABLE IF EXISTS user_settings CASCADE;
    DROP TABLE IF EXISTS user_profiles CASCADE;
  `);
}
